### PR TITLE
Put a space after the "\times" output

### PR DESCRIPTION
**Pull request by turner-eng**
Put a space after the "\times" output

### CODE REVIEW

**Comment by erwanp** [comment]
Does this fix #31  ?

**Comment by erwanp** [comment]
@turner-eng this changed the expected test output, and therefore crashed the test. [See here](https://travis-ci.com/github/erwanp/pytexit/jobs/487408277#L424).

Just make sure the output latex is properly rendered, then simply update the tests by adding the missing spaces in [test_functions.py](https://github.com/erwanp/pytexit/blob/master/pytexit/test/test_functions.py) !

**Comment by erwanp** [comment]
Some tests with `times` still fail with extra spaces : https://travis-ci.com/github/erwanp/pytexit/jobs/487643294#L605 

Do they pass locally, when running 
 ```
pytest
``` 
?

**Comment by emetor** [comment]
Closing pull request as it contains multiple issues and has partly been implemented.

**Pull request closed without merging**
